<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keyword" content="User Profile {{$global_setting['app_name']}}">
    <meta name="description" content="{{$global_setting['app_description']}}">
    <title>{{$global_setting['app_name']}}</title>
    <link rel="icon" href="{{ asset('storage/logo/' . $global_setting['app_favicon']) }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('clients/assets/libs/OwlCarousel-2/dist/assets/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('clients/dist/css/style.css') }}">
    <style>
        .footer {
            color: white;
            padding: 2rem 0;
        }

        .footer a {
            color: #ffc107;
            transition: color 0.2s;
        }

        .footer a:hover {
            color: #fff;
        }

        .footer .fw-bold {
            font-weight: 700;
        }

        .project-card {
            transition: transform 0.2s, box-shadow 0.2s; /* Smooth transition for hover effects */
            border-radius: 0.5rem; /* Rounded corners */
        }

        .project-card:hover {
            transform: translateY(-5px); /* Lift effect on hover */
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1); /* Enhance shadow on hover */
        }

        .card-img-top {
            border-top-left-radius: 0.5rem; /* Rounded corners on top */
            border-top-right-radius: 0.5rem; /* Rounded corners on top */
            object-fit: cover; /* Ensures image covers the area */
            height: 200px; /* Fixed height for consistent look */
        }

        .card-body {
            position: relative; /* Allows positioning of elements inside */
        }

        .card-title {
            font-size: 1.25rem; /* Adjust font size for title */
            margin-bottom: 1rem; /* Spacing below the title */
        }

        .card-text {
            color: #6c757d; /* Gray color for card text */
            margin-bottom: 1.5rem; /* Spacing below the content */
        }

        .card {
            border-radius: 12px;
        }

        .icon-box {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .card-body {
            background: linear-gradient(135deg, rgba(255, 223, 0, 0.1), rgba(255, 255, 255, 0.1));
        }

        .card-body .content h5 {
            text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
        }

        .card-body .content p {
            margin-bottom: 0;
        }

        .portfolio {
            background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
        }
        .card {
            background-color: white;
        }
        .card-title {
            color: #007bff;
        }
        .card-subtitle {
            color: #6c757d;
        }
        .text-warning {
            color: #ffc107 !important; /* Bootstrap warning color */
        }
        .text-secondary {
            color: #6c757d !important; /* Bootstrap secondary color */
        }
    </style>
</head>

<body>
<!------------------------------>
<!-- Header Start -->
<!------------------------------>
<header class="main-header position-fixed w-100">
    <div class="container">
        <nav class="navbar navbar-expand-xl py-0">
            <div class="logo">
                <a class="navbar-brand py-0 me-0" href="#">
                    <h4 class="text-primary fw-bold">{{$global_setting['app_name']}}</h4>
                </a>
            </div>
        </nav>
    </div>
</header>

@if($articles)
    <section class="portfolio position-relative bg-primary py-5" id="artikel">
        <div class="container position-relative">
            <div class="container mt-5">
                <div class="row justify-content-center">
                    @foreach($articles as $article) <!-- Assuming $articles for the articles section -->
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card project-card shadow-sm border-0">
                            <img src="{{ asset('storage/artikel/' . $article->image) }}" class="card-img-top" alt="Article Image">
                            <div class="card-body">
                                <h5 class="card-title font-weight-bold">{{ $article->title }}</h5>
                                <div class="card-text" id="article-content-{{ $article->id }}">
                                    <!-- Content generated by CKEditor will be inserted here -->
                                </div>
                                <a href="/artikel/{{$article->slug}}" class="btn btn-primary mt-2">Lihat Selengkapnya</a>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
    </section>
@endif


<!------------------------------>
<!-- Portfolio section End ----->
<!------------------------------>


<!------------------------------>
<!-----Footer Start------------->
<!------------------------------>
<footer class="footer bg-dark text-white py-4">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-6 mb-3">
                <h5 class="fw-bold">Kontak Kami</h5>
                <p>
                    <a href="tel:{{$global_setting['app_telp']}}" class="text-white text-decoration-none">
                        <i class="fa fa-phone me-2"></i>{{$global_setting['app_telp']}}
                    </a>
                </p>
                <p>
                    <a href="mailto:{{$global_setting['app_email']}}" class="text-white text-decoration-none">
                        <i class="fa fa-envelope me-2"></i>{{$global_setting['app_email']}}
                    </a>
                </p>
            </div>
            <div class="col-md-6 mb-3">
                <h5 class="fw-bold">Temukan Kami</h5>
                <p>
                    <a href="{{$global_setting['app_linkedin']}}" class="text-white text-decoration-none" target="_blank">
                        <i class="fa fa-linkedin me-2"></i>LinkedIn
                    </a>
                </p>
                <p>
                    <a href="{{$global_setting['app_ig']}}" class="text-white text-decoration-none" target="_blank">
                        <i class="fa fa-instagram me-2"></i>Instagram
                    </a>
                </p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-12 text-center">
                <div class="blue-light fw-500">@<span id="autodate">2024</span> <a class="text-decoration-none" href="https://sudutweb.com">PT. Sudutweb Teknologi</a> - All Rights Reserved</div>
            </div>
        </div>
    </div>
</footer>

<!------------------------------>
<!-------Footer End------------->
<!------------------------------>

<script>
    document.getElementById('autodate').textContent = new Date().getFullYear();
    function truncateContent(content, maxLength) {
        const textContent = content.replace(/<[^>]*>/g, ''); // Remove HTML tags
        return textContent.length > maxLength ? textContent.substring(0, maxLength) + '...' : textContent;
    }

    // Process article contents
    @foreach($articles as $article)
    const articleContent{{ $article->id }} = `{!! addslashes($article->content) !!}`; // Escape content
    document.getElementById('article-content-{{ $article->id }}').innerHTML = truncateContent(articleContent{{ $article->id }}, 100); // Show only 100 characters
    @endforeach

    // Initialize CKEditor for article contents
    @foreach($articles as $article)
    CKEDITOR.replace('article-editor-{{ $article->id }}', {
        on: {
            change: function(evt) {
                const editorData = this.getData();
                // Optionally handle editor data change
            }
        }
    });
    @endforeach

</script>
<!-- Include CKEditor -->
<script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
<script src="{{ asset('clients/dist/js/jquery.min.js') }}"></script>
<script src="{{ asset('clients/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('clients/assets/libs/OwlCarousel-2/dist/owl.carousel.min.js') }}"></script>
<script src="{{ asset('clients/dist/js/custom.js') }}"></script>
<script src="https://kit.fontawesome.com/1d954ea888.js"></script>

</body>

</html>
